# Generated by Django 4.2 on 2024-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('fatname', models.CharField(max_length=30)),
                ('epic', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
